# Generated by Django 5.0.4 on 2024-04-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_correct_answer',
            new_name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_correct_passes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_passes',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passes', models.IntegerField(default=0)),
                ('correct_passes', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
